# permissions for end users to edit azuremanagedmachinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azuremanagedmachinepool-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - azuremanagedmachinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - azuremanagedmachinepools/status
  verbs:
  - get
