kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha4
nodes:
# the control plane node
- role: control-plane
  extraMounts:
    - containerPath: /opt/host
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/host
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/host
      hostPath: /mnt
      readOnly: false