apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureManagedCluster
metadata:
  labels:
    "blah": "yes"
  name: capi-aks-sample
spec:
  subscriptionId: 8643025a-c059-4a48-85d0-d76f51d63a74
  resourceGroup: ace-test
  location: westus2
  name: ace-retest
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnafEQ91LfDdcpuPP52nxVkwgdDXhbZHFUsSLdfPYWsbgv+1+nThMBimYWIUmnoQnlFaz9lEbvj7gh+oZf/DEaLHNdFgI0JTAroI4hgHShGL/dg+javFp2b2TqpAmDditsA1xxsSPNsWCqSkcD1vOh6/ucX0QT50yI+lf/CuB+5HadC47b5fB0yFeipLe8HhkAdipuoSEuY5wpt37nsSDIeLVHUPRbSSPt14h1Ot2ni3vQGsyfZgGvDa/GT7tq3FZbQe7n7EIhqA8vdtey1+iztBXJIjqkO0nUwJM/aTvhbgwg1sKWH5xmb61vKQpmTP2imgcn5YMMxLr11hED13v7 ace@ace-x1
  version: 1.16.4
  nodePools:
  - name: small 
    sku: Standard_B2ms
  - name: main 
    sku: Standard_D4_v3
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capi-quickstart
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: AzureManagedCluster
    name: capi-aks-sample