name: test
on: [push, pull_request]
jobs:
    test:
        name: test cluster api provider azure
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: docker://docker.io/alexeldeib/caks-test
        - name: do
          uses: docker://docker.io/alexeldeib/caks-test
          args: /usr/local/bin/run.sh
          env:
            AZURE_AUTH_FILE: ${{ secrets.AZURE_AUTH_FILE }}
            GO111MODULE: on
        # - name: do
        #   env:
        #       AZURE_AUTH_FILE: ${{ secrets.AZURE_AUTH_FILE }}
        #       GO111MODULE: on  
        #   run: |
        #     set -eux
        #     export PATH=$GITHUB_WORKSPACE/bin:$PATH
        #     echo $PATH
        #     which kustomize
        #     which controller-gen
        #     which kind
        #     kind create cluster
        #     kind export kubeconfig --name kind
        #     kubectl config view
        #     kubectl cluster-info
        #     kubectl create -f https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.2.7/cluster-api-components.yaml
        #     kubectl create -f https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/releases/download/v0.1.5/bootstrap-components.yaml
        #     make install
        #     make test
