name: test
on: [push, pull_request]
jobs:
    test:
        name: test cluster api provider azure
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: do
          env:
              AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
              AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
              AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
              GO111MODULE: on
          run: |
            set -eux
            KUBEBUILDER_VERSION=2.2.0
            KIND_VERSION=0.6.1
            KUSTOMIZE_VERSION=3.5.1
            CONTROLLER_GEN_VERSION=0.2.4
            export PATH=$PATH:/usr/local/kubebuilder/bin:$(go env GOPATH)/bin
            go env
            go version
            sudo mkdir -p /usr/local/kubebuilder
            WORK=$(mktemp -d)
            pushd $WORK 
            go get golang.org/x/tools/cmd/goimports
            go get github.com/onsi/ginkgo/ginkgo
            go get sigs.k8s.io/kind@v${KIND_VERSION}
            rm -rf $WORK/*
            go get sigs.k8s.io/kustomize/kustomize/v3@v${KUSTOMIZE_VERSION}
            rm -rf $WORK/*
            go get sigs.k8s.io/controller-tools/cmd/controller-gen@v${CONTROLLER_GEN_VERSION}
            popd
            os=$(go env GOOS)
            arch=$(go env GOARCH)
            curl -sL https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/${os}/${arch} -o kubebuilder_${KUBEBUILDER_VERSION}_${os}_${arch}.tar.gz
            sudo tar -xzf kubebuilder_${KUBEBUILDER_VERSION}_${os}_${arch}.tar.gz -C /usr/local/kubebuilder --strip-components=1
            curl -sL https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl -o $(go env GOPATH)/bin/kubectl
            which kustomize
            which controller-gen
            which kind
            kind create cluster --verbosity 6
            kind export kubeconfig 
            kubectl config view
            kubectl cluster-info
            kubectl create -f https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.2.7/cluster-api-components.yaml
            kubectl create -f https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/releases/download/v0.1.5/bootstrap-components.yaml
            make install
            make test
